### ISSUE TITLE
PHP Fatal error: Class '....PheanstalkProxyInterface' not found in '....ParameterGenerator.php'

### ISSUE THREAD

**Issue by inanzzz** [armetiz/LeezyPheanstalkBundle#48]
Hi,

I'm not sure if whether this is related to Ocramius or Leezy but when I try to install one or both of these packages with composer I'm getting error below. I tried certain version numbers for both packages but for some reason error won't go away. Any reason why?

Thanks

```
PHP Fatal error:  Class 'Leezy\pheanstalkBundle\Proxy\PheanstalkProxyInterface' not found in /var/www/html/local/fws/vendor/ocramius/proxy-manager/src/ProxyManager/Generator/ParameterGenerator.php on line 143
```

**Comment by armetiz** [comment]
Hi @inanzzz 
The LeezyPheanstalkBundle doesn't use ProxyManager from Ocramius; I guess the problem comes from your application configuration.

Sorry;
Regards;
Thomas
