### ISSUE TITLE
Log to a specific channel

### ISSUE THREAD

**Issue by pkruithof** [armetiz/LeezyPheanstalkBundle#49]
When making heavy use of workers, there's a lot of logging going on, especially in long running commands. What's more is that all commands are logged with the `info` level, which can really clog up logs. 

I'd like to propose two possible changes:

1. Log to a specific `pheanstalk` channel. That way you can include/exclude it by monolog configuration, send it to its own separate log file, etc.
2. Add a configuration option to disable the log listener, just like the profiler.

What do you think?

**Comment by armetiz** [comment]
Hi @pkruithof 
I think the solution 1. is really great. Can you submit a Pull Request ? You will have to update `PheanstalkLogListener` class.

Regards.

**Comment by pkruithof** [comment]
Done :smile:

**Comment by armetiz** [comment]
I just pushed a 2.5.0 tag 

Thanks ;)
