### ISSUE TITLE
Docs? Practical example?

### ISSUE THREAD

**Issue by vbijlo** [armetiz/LeezyPheanstalkBundle#55]
Whats the best way to set this up? A tube per task? Or some logical tubes with the command being part of the payload, which in return calls the specific console command with its dependencies?

Or maybe another client thats listening to tubes, in return calling commands? Since long running tasks + PHP = WIZARD status.

Supervisord keeping up a command per tube, which in return calls another command to actually do something with it?

**Comment by armetiz** [comment]
Hi @vbijlo,

I'm sorry, but best practice around Beanstalkd is not the purpose of PheanstalkBundle.

Regards;
Thomas.
