### ISSUE TITLE
LeezyPheanstalkBundle for Silex

### ISSUE THREAD

**Issue by sergiors** [armetiz/LeezyPheanstalkBundle#56]
Hi, I'm writing the bundle for Silex :dancer: 

https://github.com/sergiors/pheanstalk-service-provider

**Comment by sergiors** [comment]
@armetiz Could you add for README to help who use Silex?

**Comment by armetiz** [comment]
@sergiors done : https://github.com/armetiz/LeezyPheanstalkBundle/blob/master/README.md#other

Can you create a tag on your repository ? It will be convert to a stable composer version.

**Comment by sergiors** [comment]
yep! thanks for feedback!
