### ISSUE TITLE
Compatible sf 3.0 ?

### ISSUE THREAD

**Issue by chanmix51** [armetiz/LeezyPheanstalkBundle#57]
The actual dependency status of LeezyPheanstalkBundle requires "symfony/console" version 2.x. Would it be possible to have a `~2.3|3.0` in composer.json ?

**Comment by armetiz** [comment]
I guess it should be possible. 
I have to check BC, but I think there will be no problem.

Regards.

**Comment by armetiz** [comment]
I've just created a tag `3.1.0` and push this version to master.

Regards.
