### ISSUE TITLE
Throw an exception when PheanstalkLocator finds no instances.

### ISSUE THREAD

**Issue by chanmix51** [armetiz/LeezyPheanstalkBundle#58]
When the locator has no instance to return, it should throw an exception instead of returning null.

Returning null makes people to have to test the return of the locator and then eventually throw an exception and prevent them to chain function calls.

``` php
    function sendMessage(Message $message, string $tube): self
    {
        $this->pheanstalk_locator
            ->getPheanstalk($this->readNameFromConfig())
            ->useTube($tube)
            ->put($message)
            ;

        return $this;
    }
```

This code assumes the locator throws an exception if no pheanstalk instances could be returned. I can catch the exception if I want to have an alternate execution path, or let it as is if I expect the tube to exist in the configuration.

Especially true with `getDefaultPheanstalk()`.

**Comment by armetiz** [comment]
Hi @chanmix51 

I agree with your proposition; but this will BC. 

What do you think about a PheanstalkLocatorInterface.
The default one will `return null` and the other one will `throw` an exception.

The option will be available from the `config.yml`

Regards.
