### ISSUE TITLE
Wrong proxy instance inserted

### ISSUE THREAD

**Issue by dinamic** [armetiz/LeezyPheanstalkBundle#61]
Our use case have multiple beanstalk instances and seems like the bundle can work with only the last one listed, because of a missing `clone` statement.

Have a look at the following bit from ProxyCompilerPass with my comments:

```
// get service definition by reference
$pheanstalkDef = $container->getDefinition($pheanstalk['proxy']);

// modify the service definition
$pheanstalkDef->addMethodCall('setPheanstalk', [new Definition(Pheanstalk::class, $pheanstalkConfig)]);
$pheanstalkDef->addMethodCall('setName', [$name]);

// setting an alias to it
$container->setDefinition('leezy.pheanstalk.'.$name, $pheanstalkDef);
```

If the last line is as follows, the behavior would be exactly the same:

```
$container->setAlias('leezy.pheanstalk.'.$name, $pheanstalk['proxy']);
```

Let's discuss this. If you agree with me, we can change the line to clone the definition, rather than alias it.

```
$pheanstalkDef = clone $container->getDefinition($pheanstalk['proxy']);
```

**Comment by armetiz** [comment]
Hi @dinamic 

I'm totally agree with you! 

I've just pushed a new tag 3.2.0.
I've also added a new test : https://github.com/armetiz/LeezyPheanstalkBundle/blob/master/tests/DependencyInjection/LeezyPheanstalkExtensionTest.php#L150

Thanks a lot !

**Comment by dinamic** [comment]
Cheers!
