### ISSUE TITLE
Calling primary connection "default" cause weird behaviour 

### ISSUE THREAD

**Issue by giosh94mhz** [armetiz/LeezyPheanstalkBundle#63]
I'm testing this bundle and looks good so far.

I found a minor annoyance, while creating the connection (using latest stable). I named the connection `default` instead of `primary` just to use the same convention as `doctrine` and other packages. Then I added a job in an `example-tube` and looked to the profiler page. Some kind of display loop happens and the application display 11 jobs in 22 tubes.

Renaming the connection to `primary` fix all the weird behaviour. An easy fix is to add a validation contraint in the Configuration class. Something like:
```php
    $nodeConnection
        ->validate()
        ->ifInArray(array('default'))
            ->thenInvalid('Invalid connection name "default"')
        ->end()
```

**Comment by armetiz** [comment]
Hi @giosh94mhz 
Can you take a look at the internal to find the problem and make a PR ?

At first glance, I don't understand why 'default' is an invalid name.

**Comment by giosh94mhz** [comment]
Sure, I'll dig into it ASAP, but I'm very busy in the next few days. Feel free to ping me in a while as needed.

**Comment by giosh94mhz** [comment]
I can't reproduce nor isolate the code which triggered the error. The display issue happens to me from time to time, but definitely seems not related to the name `default`. I close this issue and reopen if I find the source code.

**Comment by armetiz** [comment]
@giosh94mhz , Thank you for your analyze.
