### ISSUE TITLE
Post PUT e RESERVE event

### ISSUE THREAD

**Issue by giosh94mhz** [armetiz/LeezyPheanstalkBundle#66]
I've implemented in my project a proxy class, in order to edit the payload before is returned to the application. Wouldn't it better to have a post RESERVE command for that?

If so, PUT is the complementary command and deserve a post event too...

**Comment by armetiz** [comment]
Hi @giosh94mhz 

Events are used to inform external components that an action occurred. Event interception should not change the original operation.

In my opinion; I prefer building a application object to manage input / output to the queueing system. This object could be responsible to edit the payload.

Also, note that I don't want to add complexity on this project which is just a Symfony wrapper of a queueing adapter.

**Comment by giosh94mhz** [comment]
I know it's a simple bundle and I like it for that. The same reason for which I use beanstalkd. But I think it's a bit overwhelming to add behaviour by adding decorator (proxy) classes.

My use case is this: I create a `SecuritySubscriber` (not that secure, in fact), on PUT add an hash on RESERVE remove the hash, and if not valid replace all the payload with a "noop" token.

I don't think it adds much complexity, but feel free to close if you think it doesn't fit in the project.
