### ISSUE TITLE
Suggestion for documantation

### ISSUE THREAD

**Issue by BentCoder** [armetiz/LeezyPheanstalkBundle#67]
This is a great bundle however I believe all the events here should be explained with a few words. https://github.com/armetiz/LeezyPheanstalkBundle/blob/master/src/Resources/doc/4-events.md

**Comment by armetiz** [comment]
Hi @BentCoder 
Those events are related to beanstalkd protocol. So if you need more information about them; you should read this document : https://raw.githubusercontent.com/kr/beanstalkd/master/doc/protocol.txt

BTW; if you're interested to improve documentation; you could make a PR.

Regards;
