### ISSUE TITLE
Twig 2 support

### ISSUE THREAD

**Issue by desmax** [armetiz/LeezyPheanstalkBundle#68]
When open symfony development profiler I get
`Block "javascript" on template "@WebProfiler/Profiler/base.html.twig" does not exist.`

**Comment by armetiz** [comment]
Hi @desmax 

Are you sure the problem is coming from Twig 2 ? 
WebProfiler is part of Symfony; what is your Symfony version ?

**Comment by desmax** [comment]
@armetiz Yes, Im quite sure. Other bundles had similar error because of Twig update. 
You have this custom Jobs panel in profiler with current tubes status. This is where it brakes. 
P.S. My symfony version is 3.2.7

Will try to find problem in the code now

**Comment by desmax** [comment]
Looks like you just need to delete line 52 (`{{ block('javascript') }}`) from `src/Resources/views/Profiler/pheanstalk.html.twig`

**Comment by armetiz** [comment]
look at this commit : https://github.com/armetiz/LeezyPheanstalkBundle/commit/f36e09670a7dd2ac2ec1305312ff265de1ed62a4

thanks for report ;)
