### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by sandermarechal** [armetiz/LeezyPheanstalkBundle#69]
Can you tag a new bugfix release that contains commit f36e09670a7dd2ac2ec1305312ff265de1ed62a4 please? Currently the debug panel doesn't work due to an exception on the latest stable Symfony release. That commit fixes it:

Block "javascript" on template "@WebProfiler/Profiler/base.html.twig" does not exist.

**Comment by armetiz** [comment]
Tag 3.2.1 have been published from master; including all your PR.

**Comment by sandermarechal** [comment]
Perfect, thanks!
