### ISSUE TITLE
Symfony 3.4  DataCollectorInterface must implement reset()

### ISSUE THREAD

**Issue by digifish** [armetiz/LeezyPheanstalkBundle#71]
I upgraded to Symfony 3.4 and am now getting an depreciation message with phpunit. 

`Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since version 3.4 and will be unsupported in 4.0 for class "Leezy\PheanstalkBundle\DataCollector\PheanstalkDataCollector"`

**Comment by armetiz** [comment]
Thanks for reporting.
See https://github.com/armetiz/LeezyPheanstalkBundle/commit/4bb0c4a82408ef5308d900ce3f9b4f74d5ec44a2

Regards
