### ISSUE TITLE
Make commands and services public

### ISSUE THREAD

**Issue by new-inventor** [armetiz/LeezyPheanstalkBundle#72]
Hello!

After updating symfony to last 3.x, I see this warning:
The "leezy.pheanstalk.command.delete_job" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead. 

Not only for this command for all of it.
Before update was the deprecation message about it.

Can you fix it?
For the symfony 4.x all commands and services must be public or not used(as i understend).

For now i reinitialize commands with public option.

Thank you.

**Comment by armetiz** [comment]
could you please take a look on it and create a pull request?

**Comment by new-inventor** [comment]
yes of course.
