### ISSUE TITLE
Symfony 5 compatibility

### ISSUE THREAD

**Issue by metaer** [armetiz/LeezyPheanstalkBundle#83]
Are there plans to do Symfony 5 compatibility?

**Comment by armetiz** [comment]
Hi @metaer 
No sorry.

But if you want to work on it, you can create a Pull Request.

**Comment by pwt777** [comment]
> But if you want to work on it, you can create a Pull Request.

Ok, thanks, maybe I will create PR in the future.

**Comment by metaer** [comment]
Ok, thanks, maybe I will create PR in the future.

**Comment by armetiz** [comment]
Tga 5.0.0 from master, Sf5 support.
